#!/bin/bash

set -o xtrace
set -o nounset
set -o errexit

export PATH=dev/gems/bin:$PATH

BASE="`dirname \"$0\"`"

bundle install --gemfile $BASE/Gemfile-sass --binstubs dev/gems/bin --path dev/gems
bundle install --gemfile $BASE/Gemfile-jekyll --binstubs dev/gems/bin --path dev/gems
npm install

grunt "$@"
