# Meta
title:            Guardian beta
tagline:          ''
baseurl:          http://next.theguardian.com
author:
  name:           'The Guardian'
  url:            https://twitter.com/guardian

# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [smart]
highlighter: pygments

# Setup
permalink:        /blog/:title/
paginate:         10
paginate_path:    "/blog/page/:num/"

# Navigation
navigation:
- text: Home
  mobiletext: Home
  url: /
- text: Blog
  mobiletext: Blog
  url: /blog/
#- text: Feedback
#  mobiletext: Feedback
#  url: /feedback/

# Twitter embed plugin
gems: ['jekyll-twitter-plugin']

# Authors
authors:
  guardian:
    display_name: The Guardian
    gravatar: 
    twitter: guardian
    twitter: guardian
  paulrobertlloyd:
    display_name: Paul Lloyd
    gravatar: 0bce06bd06ee7a2c4f5500f25dcf7f18
    twitter: paulrobertlloyd
    github: paulrobertlloyd
  cantlin:
    display_name: Cantlin
    gravatar: aff34dfa0f47d7072108a836a06bb5fd
    twitter: cantlin
    github: cantlin
  anthonysullivan:
    display_name: Anthony Sullivan
    gravatar: 22d5144cc26bd0dc556c30180cea6b55
    twitter: antsullivan
    github: 
  alexbreuer:
    display_name: Alex Breuer
    gravatar: 
    image: /assets/images/ab.jpg
    twitter: ajbreuer
    github: 
  nickhaley:
    display_name: Nick Haley
    gravatar: 
    image: /assets/images/nh.jpg
    twitter: twobobswerver
    github:
  kungpochicken:
    display_name: Chris Mulholland
    gravatar: 
    twitter: kungpochicken
    github: kungpochicken
  jfitzell:
    display_name: Julian Fitzell
    gravatar: 
    twitter: jfitzell
    github: 
  kaelig:
    display_name: Kaelig Deloumeau-Prigent
    gravatar: f7e7b837bd06d6193f4ac70f17e6f44b
    twitter: kaelig
    github: kaelig
  phamann:
    display_name: Patrick Hamann
    gravatar: 276c149f793de9af4e98991ed52ff874
    twitter: phamann
    github: phamann
  theresamalone:
    display_name: Theresa Malone
    twitter: tmalone
    image: /assets/images/tm.jpg
  ceciliamarie:
    display_name: Cecilia Dobbs
    twitter: ceciliamarie
    image: /assets/images/cd.jpg
  stephanfowler:
    display_name: Stephan Fowler
    gravatar: a24a5fa8750bbc8ef2c8bf20933c4a8d
    twitter: stephanfowler
    github: stephanfowler
  wolfgangblau:
    display_name: Wolfgang Blau
    twitter: wblau
    image: /assets/images/wb.jpg
  chrisclarke:
    display_name: Chris Clarke
    twitter: mr_mr
    gravatar: 6ed0bfb73aafbb294bb90f6a47a8e1af
    github: mr_mr
  patrickstirling:
    display_name: Patrick Stirling
    gravatar: 439ffa585104f82c8901b9812cd9496d
